COVIDTESTER/AutoTest/forms.py
from django import forms

# Formulario principal para AutoTest
#
# Campos: 
#   - Código postal (Text, máximo de longitud 5)
#   - Edad (Number)
#   - Sexo (Select, tres opciones: Hombre, Mujer, Otro)
#   - Síntomas: (Booleanos, no requerido)
#       · Fiebre
#       · Tos seca
#       · Asfixia
#       · Perdida de sentidos
#   - Si los sintomas han sido repentinos (Booleano, no requerido)
#
class Formulario_AutoTest(forms.Form):
    cp = forms.CharField(
        max_length=5, 
        widget=forms.TextInput({"placeholder":"Código postal con formato '00000'"}))
    edad = forms.IntegerField()
    sexo = forms.ChoiceField(choices=(("H","Hombre"),("M","Mujer"),("O","Otro")))
    fiebre = forms.BooleanField(required=False)
    tos_seca = forms.BooleanField(required=False)
    asfixia = forms.BooleanField(required=False)
    perdida_sentidos = forms.BooleanField(required=False)
    repentino = forms.BooleanField(required=False)

# Formulario secundario, por si es positivo
#
# Campos:
#   - Si se quiere contactar (Select, dos opciones: Si, No)
#   - Telefono (Text, no requerido)
#
class Formulario_Positivo(forms.Form):
    contactar = forms.ChoiceField(
        choices=[("Si","Si"),("No","No")], 
        widget=forms.RadioSelect)
    telefono = forms.CharField(
        required=False, 
        widget=forms.TextInput({"placeholder":"Teléfono con formato '000000000'"}))

# Formulario de contacto
#
# Campos: 
#   - Asunto (Text, máximo ed longitud 200)
#   - Código postal (Text, máximo de longitud 5)
#   - Edad (Number)
#   - Sexo (Select, tres opciones: Hombre, Mujer, Otro)
#   - Email (Text)
#   - Teléfono (Text, no requerido)
#
class Formulario_Contacto(forms.Form):
    asunto = forms.CharField(
        max_length=200, 
        widget=forms.TextInput({"placeholder":"Asunto"}))
    cp = forms.CharField(
        max_length=5, 
        widget=forms.TextInput({"placeholder":"Código postal con formato '00000'"})) 
    edad = forms.IntegerField()
    sexo = forms.ChoiceField(choices=(("H","Hombre"),("M","Mujer"),("O","Otro")))
    email = forms.EmailField()
    telefono = forms.CharField(
        required=False, 
        widget=forms.TextInput({"placeholder":"Teléfono con formato '000000000'"}))

COVIDTESTER/AutoTest/templates/AutoTest.html
{% load static %}
{% include 'superior.html' %}
<!--
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     ___       __    __  .___________.  ______   .___________. _______      _______..___________.
    /   \     |  |  |  | |           | /  __  \  |           ||   ____|    /       ||           |
   /  ^  \    |  |  |  | `---|  |----`|  |  |  | `---|  |----`|  |__      |   (----``---|  |----`
  /  /_\  \   |  |  |  |     |  |     |  |  |  |     |  |     |   __|      \   \        |  |     
 /  _____  \  |  `--'  |     |  |     |  `--'  |     |  |     |  |____ .----)   |       |  |     
/__/     \__\  \______/      |__|      \______/      |__|     |_______||_______/        |__|     
                                                                                                 
 Este archivo contiene el formulario
 principal para el AutoTest. Carga contenido estático. Incluye cabecera y pié.
 
 Contiene:
 - Zona de estilos.
 - Sección de contenido principal con:
    · Header
    · Formulario
    · Enlace a condiciones.html
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-->

<style>
    #id_edad {
        -webkit-appearance: none;
        background: #f8f8f8;
        border-radius: 6px;
        border: solid 1px #e5e5e5;
        color: inherit;
        display: block;
        outline: 0;
        padding: 0 1em;
        text-decoration: none;
        width: 100%;
        height: 3em;
    }
    select {
        background-image: linear-gradient(45deg, transparent 50%, gray 50%), linear-gradient(135deg, gray 50%, transparent 50%), radial-gradient(#ddd 70%, transparent 72%);
        background-position: calc(100% - 20px) calc(1em + 2px), calc(100% - 15px) calc(1em + 2px), calc(100% - .5em) 0.5em;
        background-size: 5px 5px, 5px 5px, 1.5em 1.5em;
        background-repeat: no-repeat;
    }

    select:focus {
        background-image: linear-gradient(45deg, white 50%, transparent 50%), linear-gradient(135deg, transparent 50%, white 50%), radial-gradient(gray 70%, transparent 72%);
        background-position: calc(100% - 15px) 1em, calc(100% - 20px) 1em, calc(100% - .5em) 0.5em;
        background-size: 5px 5px, 5px 5px, 1.5em 1.5em;
        background-repeat: no-repeat;
        border-color: green;
        outline: 0;
    }
</style>

<section id="main" class="container 75%">
    <header style="padding-top: 15em;">
        <h2>
            <strong style="color: #1A4883;">AutoTest COVID-19</strong>
            {% if error %}
                <p style="color: red;">{{error}}</p>
            {% endif %}
        </h2>
        <p>Esta aplicación te permitirá hacer un seguimiento de la evolución de los
            síntomas y te dará las indicaciones y consejos a seguir en cada caso.</p>
    </header>
    <div class="box" style="background-color: #EDF0F3;">
        <form action="/AutoTest/" method="POST">{% csrf_token %}
            <div class="row uniform 100%">
                <div class="12u 12u(mobilep)">
                    <label for="id_cp">Código postal:</label>
                    <input
                        type="text"
                        name="cp"
                        minlength="5"
                        maxlength="5"
                        required="required"
                        id="id_cp"
                        pattern="\d\d\d\d\d">
                </div>
            </div>
            <div class="row uniform 100%">
                <div class="6u 12u(mobilep)">
                    <label for="id_edad">Edad:</label>
                    <input type="number" name="edad" required="required" id="id_edad" min="0">
                </div>
                <div class="6u 12u(mobilep)">
                    <label for="id_sexo">Sexo:</label>
                    <select name="sexo" id="id_sexo">
                        <option value="">--Selecciona--</option>
                        <option value="H">Hombre</option>
                        <option value="M">Mujer</option>
                        <option value="O">Otro</option>
                    </select>
                </div>
            </div>
            <div class="row uniform 100%">
                <div class="12u 12u(mobilep)" style="text-align: center;">
                    <h4>Indique si ha padecido alguno de los sigientes síntomas, y en caso de
                        haberlos padecido, indique si fué de manera repentina:</h4>
                </div>
            </div>
            <div class="row uniform 100%">
                <div class="3u 12u(mobilep)">
                    <label for="id_fiebre">
                        <input
                            type="checkbox"
                            name="fiebre"
                            id="id_fiebre"
                            style="opacity: 100%; margin-right: 0;">
                        <span>Fiebre</span>
                    </label>
                </div>
                <div class="3u 12u(mobilep)">
                    <label for="id_tos_seca">
                        <input
                            type="checkbox"
                            name="tos_seca"
                            id="id_tos_seca"
                            style="opacity: 100%; margin-right: 0;">
                        <span>Tos seca</span>
                    </label>
                </div>
                <div class="3u 12u(mobilep)">
                    <label for="id_asfixia">
                        <input
                            type="checkbox"
                            name="asfixia"
                            id="id_asfixia"
                            style="opacity: 100%; margin-right: 0;">
                        <span>Asfixia</span>
                    </label>
                </div>
                <div class="3u 12u(mobilep)">
                    <label for="id_perdida_sentidos">
                        <input
                            type="checkbox"
                            name="perdida_sentidos"
                            id="id_perdida_sentidos"
                            style="opacity: 100%; margin-right: 0;">
                        <span>Perdida del gusto</span>
                    </label>
                </div>
            </div>
            <div class="row uniform 100%">
                <div class="3u 12u(mobilep)">
                    <label for="id_repentino">
                        <input
                            type="checkbox"
                            name="repentino"
                            id="id_repentino"
                            style="opacity: 100%; margin-right: 0;">
                        <span>¿Ha sido repentino?</span>
                    </label>
                </div>
            </div>
            <div class="row uniform">
                <div class="12u">
                    <ul class="actions align-center">
                        <li><input type="submit" value="Enviar" style="background-color: #154481;"/></li>
                        <li><input
                            type="reset"
                            value="Limpiar"
                            style="background-color: #E2EEF6; color: #24536B;"/></li>
                        <li>
                            <a href="javascript:history.back()" style="color: #24536B;">Volver</a>
                        </li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
    <p style="text-align: center;">El uso de este servicio supone la aceptación de
        los términos y la política de privacidad descritos en
        <a href="{% url 'condiciones' %}">'Ver las condiciones y políticas'</a>
    </p>
</section>

{% include 'inferior.html' %}

COVIDTESTER/AutoTest/templates/contacto.html
{% load static %}
{% include 'superior.html' %}
<!--
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
  ______   ______   .__   __. .___________.     ___        ______ .___________.  ______   
 /      | /  __  \  |  \ |  | |           |    /   \      /      ||           | /  __  \  
|  ,----'|  |  |  | |   \|  | `---|  |----`   /  ^  \    |  ,----'`---|  |----`|  |  |  | 
|  |     |  |  |  | |  . `  |     |  |       /  /_\  \   |  |         |  |     |  |  |  | 
|  `----.|  `--'  | |  |\   |     |  |      /  _____  \  |  `----.    |  |     |  `--'  | 
 \______| \______/  |__| \__|     |__|     /__/     \__\  \______|    |__|      \______/ 

 Este archivo contiene un formulario de contacto que se utiliza para contactar con profesionales sanitarios.

 Contiene: 
 - Zona de estilos
 - Titulo
 - Formulario en si
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-->

<style>
    #id_edad {
        -webkit-appearance: none;
        background: #f8f8f8;
        border-radius: 6px;
        border: solid 1px #e5e5e5;
        color: inherit;
        display: block;
        outline: 0;
        padding: 0 1em;
        text-decoration: none;
        width: 100%;
        height: 3em;
    }
    select {
        background-image: linear-gradient(45deg, transparent 50%, gray 50%), linear-gradient(135deg, gray 50%, transparent 50%), radial-gradient(#ddd 70%, transparent 72%);
        background-position: calc(100% - 20px) calc(1em + 2px), calc(100% - 15px) calc(1em + 2px), calc(100% - .5em) 0.5em;
        background-size: 5px 5px, 5px 5px, 1.5em 1.5em;
        background-repeat: no-repeat;
    }

    select:focus {
        background-image: linear-gradient(45deg, white 50%, transparent 50%), linear-gradient(135deg, transparent 50%, white 50%), radial-gradient(gray 70%, transparent 72%);
        background-position: calc(100% - 15px) 1em, calc(100% - 20px) 1em, calc(100% - .5em) 0.5em;
        background-size: 5px 5px, 5px 5px, 1.5em 1.5em;
        background-repeat: no-repeat;
        border-color: green;
        outline: 0;
    }
</style>

<section id="main" class="container 75%">
    <header style="padding-top: 15em;">
        <h2>
            <strong style="color: #1A4883;">Formulario de contacto</strong>
            {% if error %}
                <p style="color: red;">{{error}}</p>
            {% endif %}
        </h2>
        <p>Mediante este formulario podrá aportar los datos necesarios para poder contactar con profesionales sanitarios.</p>
    </header>
    <div class="box" style="background-color: #EDF0F3;">
        <form action="/contacto/" method="POST">{% csrf_token %}
            <div class="row uniform 100%">
                <div class="12u 12u(mobilep)">
                    <label for="id_asunto">Asunto:</label>
                    <input type="text" name="asunto" placeholder="Asunto" required="required" id="id_asunto" >
                </div>
            </div>
            <div class="row uniform 100%">
                <div class="12u 12u(mobilep)">
                    <label for="id_cp">Código postal:</label>
                    <input type="text" name="cp" placeholder="Código postal con formato '00000'" minlength="5" maxlength="5" required="required" id="id_cp" pattern="\d\d\d\d\d">
                </div>
            </div>
            <div class="row uniform 100%">
                <div class="6u 12u(mobilep)">
                    <label for="id_edad">Edad:</label>
                    <input type="number" name="edad" required="required" id="id_edad" min="0">
                </div>
                <div class="6u 12u(mobilep)">
                    <label for="id_sexo">Sexo:</label>
                    <select name="sexo" id="id_sexo">
                        <option value="">--Selecciona--</option>
                        <option value="H">Hombre</option>
                        <option value="M">Mujer</option>
                        <option value="O">Otro</option>
                    </select>
                </div>
            </div>
            <div class="row uniform 100%">
                <div class="6u 12u(mobilep)">
                    <label for="id_email">Email:</label>
                    <input type="email" name="email" placeholder="Email con formato 'xxxx@xxx.xx'"  required id="id_email">
                </div>
                <div class="6u 12u(mobilep)">
                    <label for="id_telefono">Telefono:</label>
                    <input type="text" name="telefono" placeholder="Teléfono con formato &#x27;000000000&#x27;" id="id_telefono">
                </div>
            </div>
            <div class="row uniform">
                <div class="12u">
                    <ul class="actions align-center">
                        <li><input type="submit" value="Enviar" style="background-color: #154481;"/></li>
                        <li><input type="reset" value="Limpiar" style="background-color: #E2EEF6; color: #24536B;"/></li>
                        <li>
                            <a href="javascript:history.back()" style="color: #24536B;">Volver</a>
                        </li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
    <p style="text-align: center;">El uso de este servicio supone la aceptación de
        los términos y la política de privacidad descritos en
        <a href="{% url 'condiciones' %}">'Ver las condiciones y políticas'</a>
    </p>
</section>

{% include 'inferior.html' %}

COVIDTESTER/AutoTest/templates/index.html
{% load static %}
{% include 'superior.html' %}
<!--
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
 __  .__   __.  __    ______  __    ______   
|  | |  \ |  | |  |  /      ||  |  /  __  \  
|  | |   \|  | |  | |  ,----'|  | |  |  |  | 
|  | |  . `  | |  | |  |     |  | |  |  |  | 
|  | |  |\   | |  | |  `----.|  | |  `--'  | 
|__| |__| \__| |__|  \______||__|  \______/  

 Este archivo será la página de inicio de la app.
 Carga contenido estático.
 Incluye cabecera y pié.

 Contiene: 
 - Sección banner
 - Sección contenido principal (Vacía, al menos por ahora)
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-->

<!-- Banner -->
<section id="banner" style="padding-top: 5em;">
    <h2>COVIDTESTER</h2>
    {% if resultado %}
        {% if resultado == "positivo" %}
            {% if contacto == True %}
                <h3 style="color: red;">Profesionales sanitarios contactarán con usted lo antes posible.</h3>
            {% else %}
                <h3 style="color: red;">Profesionales sanitarios no contactarán con usted.</h3>
            {% endif %}
        {% endif %}
        <p>En la nueva página que se le ha abierto puede ver consejos sobre como actuar.</p>
        <p>Si usted u otra persona desea realizar el test de nuevo puede hacerlo aquí: </p>
    {% else %}
        {% if contactar_enviado == True %}
            <h3 style="color: red;">Profesionales sanitarios contactarán con usted lo antes posible.</h3>
        {% endif %}
        <h3>Si tienes síntomas de coronavirus SARS CoV-2 o has estado en contacto con una persona afectada deberías hacer un control y seguimiento diario de tus síntomas.</h3>
        <p>Aquí puedes encontrar nuestro test online gratuito:</p>
    {% endif %}
    <ul class="actions">
        <li>
            <a href="{% url 'preAutoTest' %}" class="button special">Hacer test</a>
        </li>
    </ul>
</section>

<!-- Main -->
<section id="main" class="container" style="text-align: center; padding-top: 0; padding-bottom: 0;">
    <table class="table table-hover table-dark" >
        <thead style="background-color: #EDF0F3;">
            <tr>
                <th scope="col" style="text-align: center;">Confirmados</th>
                <th scope="col" style="text-align: center;">Hospitalizados</th>
                <th scope="col" style="text-align: center;">Muertes</th>
                <th scope="col" style="text-align: center;">Recuperados</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{confirmados}}</td>
                <td>{{hospitalizados}}</td>
                <td>{{muertes}}</td>
                <td>{{recuperados}}</td>
            </tr>
            <tr style="color: yellow;">
                <td colspan="4"><i>Información del Ministerio de Sanidad Gobierno de España, datos de Navarra. Última actualización: {{fecha_actualizacion}}</i></td>
            </tr>
        </tbody>
    </table>
</section>

{% include 'inferior.html' %}

COVIDTESTER/AutoTest/templates/inferior.html
{% load static %}
<!--
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
 _______   ______     ______   .___________. _______ .______      
|   ____| /  __  \   /  __  \  |           ||   ____||   _  \     
|  |__   |  |  |  | |  |  |  | `---|  |----`|  |__   |  |_)  |    
|   __|  |  |  |  | |  |  |  |     |  |     |   __|  |      /     
|  |     |  `--'  | |  `--'  |     |  |     |  |____ |  |\  \----.
|__|      \______/   \______/      |__|     |_______|| _| `._____|

 Este archivo será la parte inferior estática de toda la app.
 Carga contenido estático.

 Contiene: 
 - Sección de contacto
 - Pié de página
 - Scrits (Bootstrap)
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-->

<!-- CTA -->
<section id="cta" style="padding: 1em 0 0.5em 0;">
    <h2>Contácta con nosotrso para ser atendido por servicios sanitarios.</h2>
    <ul class="actions">
        <li>
            <a href="{% url 'contacto' %}" class="button alt">Contactar</a>
        </li>
    </ul>
</section>

<!-- Footer -->
<footer id="footer" style="padding: 1em 0 1em 0;">
    <ul class="copyright">
        <li>&copy; Untitled.</li>
    </ul>
</footer>

</div>

<!-- Scripts -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.dropotron.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.scrollgress.min.js' %}"></script>
<script src="{% static 'assets/js/skel.min.js' %}"></script>
<script src="{% static 'assets/js/util.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

COVIDTESTER/AutoTest/templates/resultado.html
{% load static %}
{% include 'superior.html' %}
<!--
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
.______       _______      _______. __    __   __      .___________.     ___       _______    ______   
|   _  \     |   ____|    /       ||  |  |  | |  |     |           |    /   \     |       \  /  __  \  
|  |_)  |    |  |__      |   (----`|  |  |  | |  |     `---|  |----`   /  ^  \    |  .--.  ||  |  |  | 
|      /     |   __|      \   \    |  |  |  | |  |         |  |       /  /_\  \   |  |  |  ||  |  |  | 
|  |\  \----.|  |____ .----)   |   |  `--'  | |  `----.    |  |      /  _____  \  |  '--'  ||  `--'  | 
| _| `._____||_______||_______/     \______/  |_______|    |__|     /__/     \__\ |_______/  \______/ 

 Este archivo es la página a la que se llega tras realizar el AutoTest, independientemente 
 del resultado.

 Contiene: 
 - Zona de estilos
 - Header (dependiendo de resultado)
 - Formulario (dependiendo de resultado)
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-->
<style>
    #id_edad {
        -webkit-appearance: none;
        background: #f8f8f8;
        border-radius: 6px;
        border: solid 1px #e5e5e5;
        color: inherit;
        display: block;
        outline: 0;
        padding: 0 1em;
        text-decoration: none;
        width: 100%;
        height: 3em;
    }
    select {
        background-image: linear-gradient(45deg, transparent 50%, gray 50%), linear-gradient(135deg, gray 50%, transparent 50%), radial-gradient(#ddd 70%, transparent 72%);
        background-position: calc(100% - 20px) calc(1em + 2px), calc(100% - 15px) calc(1em + 2px), calc(100% - .5em) 0.5em;
        background-size: 5px 5px, 5px 5px, 1.5em 1.5em;
        background-repeat: no-repeat;
    }
    
    select:focus {
        background-image: linear-gradient(45deg, white 50%, transparent 50%), linear-gradient(135deg, transparent 50%, white 50%), radial-gradient(gray 70%, transparent 72%);
        background-position: calc(100% - 15px) 1em, calc(100% - 20px) 1em, calc(100% - .5em) 0.5em;
        background-size: 5px 5px, 5px 5px, 1.5em 1.5em;
        background-repeat: no-repeat;
        border-color: green;
        outline: 0;
    }
</style>

<script>
    function si_contactar() {
        document.getElementById("telefono").style.visibility = "visible";
    }
    function no_contactar() {
        document.getElementById("telefono").style.visibility = "hidden";
    }
</script>

<section id="main" class="container 75%">
    <header style="padding-top: 15em;">
        <h2>
            <strong style="color: #1A4883;">¿Estoy contagiado?</strong>
        </h2>
        {% if resultado == True %}
            <h3 style="color: red;">LA INFORMACIÓN QUE HAS APORTADO SUGIERE QUE ES POSIBLE QUE ESTÉ PADECIENDO COVID-19</h3>
            <h1>¿Desea que contacten con usted profesionales sanitarios?</h1>
        {% else %}
            <h3 style="color: green;">LA INFORMACIÓN QUE HAS APORTADO NO SUGIERE QUE ES ESTÉ PADECIENDO COVID-19</h3>
        {% endif %}
    </header>
    <div class="box" style="background-color: #EDF0F3;">
        {% if resultado == True %}
            <p style="text-align: center;">Es posible que haya contraído usted coronavirus. Si lo desea, puede ser usted contactado por personal sanitario.</p>
            <form action="/posible_positivo/" method="POST">{% csrf_token %}
                <div class="row uniform 100%">
                    <div class="12u 12u(mobilep)">
                        <label for="id_contactar_0">Contactar:</label>
                        <label for="id_contactar_0">
                            Si <input onclick="si_contactar()" type="radio" name="contactar" value="Si" required="required" id="id_contactar_0" style="opacity: 100%; margin-right: 0;">
                        </label>
                        <label for="id_contactar_1">
                            No <input onclick="no_contactar()" type="radio" name="contactar" value="No" required="required" id="id_contactar_1" style="opacity: 100%; margin-right: 0;">
                        </label>
                    </div>
                </div>
                <div id="telefono" class="row uniform 100%" style="visibility: hidden;">
                    <div class="12u 12u(mobilep)">
                        <label for="id_telefono">Telefono:</label>
                        <input type="text" name="telefono" placeholder="Teléfono con formato '000000000'" minlength="9" maxlength="9" id="id_telefono" pattern="(6|7)[ -]*([0-9][ -]*){8}">
                    </div>
                </div>
                <div class="row uniform">
                    <p style="margin-bottom: 0; text-align: center;">Agradecemos su colaboración. Con la información que ha aportado se elaborarán estdisticas para ayudar a combatir la pandemia.</p>
                    <div class="12u">
                        <ul class="actions align-center">
                            <li><input type="submit" value="Aceptar" style="background-color: #154481;"/></li>
                            <li><input type="reset" value="Limpiar" style="background-color: #E2EEF6; color: #24536B;"/></li>
                            <li>
                                <a href="javascript:history.back()" style="color: #24536B;">Volver</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </form>
        {% else %}
            <p style="text-align: center;">No parece que haya contraído usted coronavirus. <strong>A continuación se abrirá a otra página en la que se explica cómo actuar ante la situación actual.</strong></p>
            <p style="text-align: center;">Agradecemos su colaboración. Con la información que ha aportado se elaborarán estdisticas para ayudar a combatir la pandemia.</p>
            <form action="/negativo/" method="POST">{% csrf_token %}
                <div class="row uniform">
                    <div class="12u">
                        <ul class="actions align-center">
                            <li><input type="submit" value="Aceptar" style="background-color: #154481;"/></li>
                            <li>
                                <a href="javascript:history.back()" style="color: #24536B;">Volver</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </form>
        {% endif %}
    </div>
    <p style="text-align: center;">El uso de este servicio supone la aceptación de los términos y la política de privacidad descritos en
    <a href="{% url 'condiciones' %}">'Ver las condiciones y políticas'</a></p>
</section>

{% include 'inferior.html' %}